// frontend/src/components/pet/ThinkingDots.vue
<template>
  <div v-if="visible" class="thinking-dots">
    <span v-for="i in 3" :key="i" class="dot" :style="{ animationDelay: `${(i - 1) * 0.15}s` }" />
  </div>
</template>

<script setup lang="ts">
defineProps<{ visible: boolean }>()
</script>

<style scoped>
.thinking-dots {
  position: absolute; top: 18%; left: 50%;
  transform: translateX(-50%); z-index: 12;
  display: flex; gap: 6px; pointer-events: none;
}
.dot {
  display: inline-block; width: 8px; height: 8px;
  border-radius: 50%; background: #999;
  animation: thinking-bounce 1.4s infinite ease-in-out both;
}
</style>

// frontend/src/components/pet/ThinkingDots.tsx
function ThinkingDots({ visible }: { visible: boolean }) {
  if (!visible) return null

  return (
    <div style={{
      position: 'absolute',
      top: '18%',
      left: '50%',
      transform: 'translateX(-50%)',
      zIndex: 12,
      display: 'flex',
      gap: 6,
      pointerEvents: 'none',
    }}>
      {[0, 1, 2].map((i) => (
        <span
          key={i}
          style={{
            display: 'inline-block',
            width: 8,
            height: 8,
            borderRadius: '50%',
            background: '#999',
            animation: `thinking-bounce 1.4s ${i * 0.15}s infinite ease-in-out both`,
          }}
        />
      ))}
    </div>
  )
}

export default ThinkingDots
