// frontend/src/pages/settings/DashboardPage.vue
<template>
  <div class="page-root">
    <div class="page-header">
      <h2 class="page-title">仪表盘</h2>
      <n-tag type="info" size="small" round :bordered="false">实时</n-tag>
    </div>

    <n-tabs v-model:value="tab" type="segment" animated>
      <n-tab-pane name="overview" tab="概览" />
      <n-tab-pane name="emotion" tab="情绪" />
      <n-tab-pane name="decision" tab="决策" />
    </n-tabs>

    <n-skeleton v-if="!features" text :repeat="4" style="margin-top: 24px;" />

    <!-- Overview -->
    <template v-if="tab === 'overview' && features">
      <n-grid :cols="4" :x-gap="16" :y-gap="16" style="margin-top: 20px;">
        <n-gi>
          <n-card size="small" :bordered="false" class="stat-card">
            <n-statistic label="接受率" :value="features.relationship.overall_accept_rate > 0 ? (features.relationship.overall_accept_rate * 100).toFixed(0) : '--'" />
            <template #header-extra><n-icon size="20" color="#4f6ef7"><TrendingUpOutline /></n-icon></template>
          </n-card>
        </n-gi>
        <n-gi>
          <n-card size="small" :bordered="false" class="stat-card">
            <n-statistic label="连续工作">
              {{ features.user.continuous_work_min > 0 ? features.user.continuous_work_min.toFixed(0) + ' 分钟' : '未工作' }}
            </n-statistic>
            <template #header-extra><n-icon size="20" color="#f59e0b"><DesktopOutline /></n-icon></template>
          </n-card>
        </n-gi>
        <n-gi>
          <n-card size="small" :bordered="false" class="stat-card">
            <n-statistic label="今日行动">
              {{ learning?.metrics.total_today ?? '--' }} 次
            </n-statistic>
            <template #header-extra><n-icon size="20" color="#10b981"><FlashOutline /></n-icon></template>
          </n-card>
        </n-gi>
        <n-gi>
          <n-card size="small" :bordered="false" class="stat-card">
            <n-statistic label="最近拒绝">
              {{ features.relationship.recent_rejections }} 次
            </n-statistic>
            <template #header-extra><n-icon size="20" color="#ef4444"><AlertCircleOutline /></n-icon></template>
          </n-card>
        </n-gi>
      </n-grid>

      <n-grid :cols="2" :x-gap="20" style="margin-top: 20px;">
        <n-gi>
          <n-card title="5 维驱力" :bordered="false" size="small">
            <div class="drive-bars">
              <div v-for="d in driveBars" :key="d.label" class="drive-row">
                <span class="drive-label">{{ d.label }}</span>
                <n-progress
                  :percentage="Math.round(d.value * 100)"
                  :color="d.color"
                  :height="8"
                  :border-radius="4"
                  :show-indicator="false"
                  processing
                />
                <span class="drive-val">{{ (d.value * 100).toFixed(0) }}%</span>
              </div>
            </div>
          </n-card>
        </n-gi>
        <n-gi>
          <n-card title="6 维内源需求" :bordered="false" size="small">
            <div class="drive-bars">
              <div v-for="n in needBars" :key="n.label" class="drive-row">
                <span class="drive-label">{{ n.label }}</span>
                <n-progress
                  :percentage="Math.round(n.value * 100)"
                  :color="n.color"
                  :height="8"
                  :border-radius="4"
                  :show-indicator="false"
                  processing
                />
                <span class="drive-val">{{ (n.value * 100).toFixed(0) }}%</span>
              </div>
            </div>
          </n-card>
        </n-gi>
      </n-grid>

      <n-card title="互动关系" :bordered="false" size="small" style="margin-top: 20px;">
        <n-grid :cols="3" :x-gap="16">
          <n-gi><div class="rel-item"><span class="rel-label">冷落时长</span><span class="rel-value">{{ (features.relationship.neglect_hours * 60).toFixed(0) }} 分钟</span></div></n-gi>
          <n-gi><div class="rel-item"><span class="rel-label">消息趋势</span><span class="rel-value">{{ features.user.length_trend < -0.2 ? '变短 ↓' : features.user.length_trend > 0.2 ? '变长 ↑' : '稳定' }}</span></div></n-gi>
          <n-gi><div class="rel-item"><span class="rel-label">亲密度趋势</span><span class="rel-value">{{ features.relationship.intimacy_trend < -0.1 ? '降温 ↓' : features.relationship.intimacy_trend > 0.1 ? '升温 ↑' : '稳定' }}</span></div></n-gi>
        </n-grid>
      </n-card>
    </template>

    <!-- Emotion -->
    <template v-if="tab === 'emotion' && emotion">
      <n-card :bordered="false" size="small" style="margin-top: 20px;">
        <div class="emotion-header">
          <n-avatar :size="64" color="#e6f0ff">{{ emotionIcon(emotion.primary) }}</n-avatar>
          <div>
            <div class="emotion-label">{{ primaryLabel(emotion.primary) }}</div>
            <div class="emotion-pad">愉悦 {{ emotion.valence.toFixed(2) }} · 唤醒 {{ emotion.arousal.toFixed(2) }} · 支配 {{ emotion.dominance.toFixed(2) }}</div>
            <div class="emotion-strength">强度 {{ (emotion.intensity * 100).toFixed(0) }}%</div>
          </div>
        </div>
      </n-card>

      <n-card title="8 维情绪向量" :bordered="false" size="small" style="margin-top: 20px;">
        <div class="drive-bars">
          <div v-for="e in emotionBars" :key="e.label" class="drive-row">
            <span class="drive-label">{{ e.label }}</span>
            <n-progress :percentage="Math.round(e.value * 100)" :color="e.color" :height="8" :border-radius="4" :show-indicator="false" processing />
            <span class="drive-val">{{ (e.value * 100).toFixed(0) }}%</span>
          </div>
        </div>
      </n-card>
    </template>

    <!-- Decision -->
    <template v-if="tab === 'decision' && features">
      <n-card title="最近决策溯源" :bordered="false" size="small" style="margin-top: 20px;">
        <template v-if="features.last_decision">
          <div class="decision-main">
            <span class="decision-action">{{ actionLabel(features.last_decision.action) }}</span>
            <span class="decision-score">score {{ features.last_decision.score.toFixed(3) }}</span>
          </div>
          <div class="decision-meta">
            {{ features.last_decision.routed_llm ? 'LLM 兜底决策' : 'System 1 快速决策' }} · 来源: {{ features.last_decision.source || '--' }}
          </div>
          <n-space style="margin-top: 8px;">
            <n-tag v-if="features.last_decision.routed_llm" type="warning" size="small" round :bordered="false">LLM</n-tag>
            <n-tag v-if="features.last_decision.source === 'care'" type="error" size="small" round :bordered="false">关怀</n-tag>
            <n-tag v-if="features.last_decision.source === 'casual'" type="info" size="small" round :bordered="false">闲聊</n-tag>
            <n-tag v-if="features.last_decision.source === 'knowledge_gap'" type="success" size="small" round :bordered="false">好奇</n-tag>
          </n-space>
        </template>
        <div v-else class="empty-text">等待首次决策...</div>
      </n-card>

      <n-grid :cols="2" :x-gap="20" style="margin-top: 20px;">
        <n-gi>
          <n-card title="当前关键因子" :bordered="false" size="small">
            <div v-for="f in factorItems" :key="f.label" class="factor-row">
              <span class="factor-label">{{ f.label }}</span>
              <span class="factor-value">{{ f.value }}</span>
            </div>
          </n-card>
        </n-gi>
        <n-gi>
          <n-card title="学习统计" :bordered="false" size="small" v-if="learning">
            <n-grid :cols="2" :x-gap="12" :y-gap="12">
              <n-gi><div class="metric-box"><div class="metric-num">{{ learning.principles_count }}</div><div class="metric-lbl">策略</div></div></n-gi>
              <n-gi><div class="metric-box"><div class="metric-num">{{ learning.active_threads }}</div><div class="metric-lbl">线程</div></div></n-gi>
              <n-gi><div class="metric-box"><div class="metric-num">{{ learning.active_inquiries }}</div><div class="metric-lbl">探索目标</div></div></n-gi>
              <n-gi><div class="metric-box"><div class="metric-num">{{ learning.patterns_count }}</div><div class="metric-lbl">模式</div></div></n-gi>
            </n-grid>
          </n-card>
        </n-gi>
      </n-grid>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import {
  NGrid, NGi, NCard, NTabs, NTabPane, NTag, NProgress,
  NSpace, NAvatar, NStatistic, NIcon, NSkeleton,
} from 'naive-ui'
import {
  TrendingUpOutline, DesktopOutline, FlashOutline, AlertCircleOutline,
} from '@vicons/ionicons5'
import { getFeatures, getLearningOverview, getEmotion, FeaturesViewModel, LearningOverview, EmotionViewModel } from '../../stores/api'

type Tab = 'overview' | 'emotion' | 'decision'
const tab = ref<Tab>('overview')

const features = ref<FeaturesViewModel | null>(null)
const learning = ref<LearningOverview | null>(null)
const emotion = ref<EmotionViewModel | null>(null)

function refresh() {
  getFeatures().then(f => features.value = f).catch(() => {})
  getLearningOverview().then(l => learning.value = l).catch(() => {})
  getEmotion().then(e => emotion.value = e).catch(() => {})
}
let timer: ReturnType<typeof setInterval>
onMounted(() => { refresh(); timer = setInterval(refresh, 5000) })
onUnmounted(() => clearInterval(timer))

const driveBars = computed(() => {
  if (!features.value) return []
  const d = features.value.drives
  return [
    { label: '社交', value: d.social, color: '#f472b6' },
    { label: '关怀', value: d.care, color: '#ef4444' },
    { label: '好奇', value: d.curious ?? 0, color: '#60a5fa' },
    { label: '安静', value: d.quiet, color: '#a78bfa' },
    { label: '探索', value: d.explore, color: '#34d399' },
  ]
})

const needBars = computed(() => {
  if (!features.value) return []
  const n = features.value.needs
  return [
    { label: '陪伴', value: n.companionship, color: '#f472b6' },
    { label: '关怀', value: n.care, color: '#ef4444' },
    { label: '玩耍', value: n.play, color: '#34d399' },
    { label: '好奇', value: n.curiosity, color: '#60a5fa' },
    { label: '休息', value: n.rest, color: '#a78bfa' },
    { label: '自主', value: n.autonomy, color: '#fbbf24' },
  ]
})

const emotionBars = computed(() => {
  if (!emotion.value) return []
  const v = emotion.value.vector
  return [
    { label: '情感', value: v.affection, color: '#f472b6' },
    { label: '担忧', value: v.worry, color: '#fbbf24' },
    { label: '好奇', value: v.curiosity, color: '#60a5fa' },
    { label: '困倦', value: v.sleepiness, color: '#a78bfa' },
    { label: '贪玩', value: v.playfulness, color: '#34d399' },
    { label: '寂寞', value: v.loneliness, color: '#f87171' },
    { label: '自信', value: v.confidence, color: '#818cf8' },
    { label: '烦躁', value: v.annoyance, color: '#fb923c' },
  ]
})

const factorItems = computed(() => {
  if (!features.value) return []
  const f = features.value
  return [
    { label: 'App', value: `${f.user.app_category} (${f.user.window_subtype || '-'})` },
    { label: '工作中', value: f.user.is_working ? '是' : '否' },
    { label: '时段接受率', value: `${(f.relationship.time_window_accept * 100).toFixed(0)}%` },
    { label: '距上次消息', value: `${f.user.time_since_chat_min.toFixed(0)} 分钟` },
    { label: '策略 / 模式', value: `${f.task.principle_count} / ${f.task.pattern_count}` },
    { label: '冷却', value: `${(f.task.cooldown_norm * 100).toFixed(0)}%` },
  ]
})

function emotionIcon(p: string) { const m: Record<string, string> = { joy: '😊', sadness: '😢', anger: '😠', fear: '😨', surprise: '😲', disgust: '🤢', neutral: '😐' }; return m[p] || '😐' }
function primaryLabel(p: string) { const m: Record<string, string> = { joy: '开心', sadness: '难过', anger: '生气', fear: '恐惧', surprise: '惊讶', disgust: '厌恶', neutral: '平静' }; return m[p] || p }
function actionLabel(a: string) { const m: Record<string, string> = { speak_casual: '闲聊', speak_care: '关心', speak_inquiry: '提问', care_rest: '催睡', care_meal: '催饭', care_hydration: '催喝水', care_health: '健康提醒', care_encourage: '鼓励', care_social: '社交提醒', observe: '观察', reflect: '反思', analyze_patterns: '分析', none: '安静' }; return m[a] || a }
</script>

<style scoped>
.page-root { height: 100%; overflow-y: auto; }
.page-header { display: flex; align-items: center; gap: 12px; margin-bottom: 4px; }
.page-title { font-size: 22px; font-weight: 700; margin: 0; color: #1a1a2e; }
.stat-card :deep(.n-card__content) { padding: 16px 20px; }
.drive-bars { display: flex; flex-direction: column; gap: 12px; }
.drive-row { display: flex; align-items: center; gap: 10px; }
.drive-label { width: 36px; font-size: 13px; color: #6b7280; text-align: right; flex-shrink: 0; }
.drive-val { width: 36px; font-size: 12px; color: #9ca3af; text-align: right; flex-shrink: 0; }
.rel-item { text-align: center; }
.rel-label { display: block; font-size: 12px; color: #9ca3af; margin-bottom: 4px; }
.rel-value { font-size: 15px; font-weight: 600; color: #1a1a2e; }
.emotion-header { display: flex; align-items: center; gap: 16px; }
.emotion-label { font-size: 24px; font-weight: 700; color: #1a1a2e; }
.emotion-pad { font-size: 13px; color: #6b7280; margin-top: 2px; }
.emotion-strength { font-size: 12px; color: #9ca3af; margin-top: 2px; }
.decision-main { margin-bottom: 4px; }
.decision-action { font-size: 20px; font-weight: 700; }
.decision-score { font-size: 13px; color: #9ca3af; margin-left: 8px; font-weight: 400; }
.decision-meta { font-size: 13px; color: #6b7280; }
.factor-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f3f4f6; }
.factor-row:last-child { border-bottom: none; }
.factor-label { font-size: 13px; color: #6b7280; }
.factor-value { font-size: 13px; font-weight: 500; color: #1a1a2e; }
.metric-box { text-align: center; padding: 12px; background: #f8fafc; border-radius: 8px; }
.metric-num { font-size: 22px; font-weight: 700; color: #1a1a2e; }
.metric-lbl { font-size: 12px; color: #9ca3af; margin-top: 2px; }
.empty-text { color: #9ca3af; padding: 20px 0; }
</style>

// desktop-pet/frontend/src/pages/settings/DashboardPage.tsx
import { useEffect, useState, useCallback } from 'react'
import { getFeatures, getLearningOverview, getEmotion, FeaturesViewModel, LearningOverview, EmotionViewModel } from '../../store/api'
import RadarChart from '../../components/settings/RadarChart'
import StatCard from '../../components/settings/StatCard'

type Tab = 'overview' | 'emotion' | 'decision'

export default function DashboardPage() {
  const [tab, setTab] = useState<Tab>('overview')
  const [features, setFeatures] = useState<FeaturesViewModel | null>(null)
  const [learning, setLearning] = useState<LearningOverview | null>(null)
  const [emotion, setEmotion] = useState<EmotionViewModel | null>(null)

  const refresh = useCallback(() => {
    getFeatures().then(setFeatures).catch(() => {})
    getLearningOverview().then(setLearning).catch(() => {})
    getEmotion().then(setEmotion).catch(() => {})
  }, [])

  useEffect(() => { refresh(); const t = setInterval(refresh, 5000); return () => clearInterval(t) }, [refresh])

  const tabs: { key: Tab; label: string }[] = [
    { key: 'overview', label: '概览' },
    { key: 'emotion', label: '情绪' },
    { key: 'decision', label: '决策' },
  ]

  return (
    <div>
      <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 16 }}>仪表盘</h2>

      {/* Tab bar */}
      <div style={{ display: 'flex', gap: 4, marginBottom: 20, borderBottom: '1px solid var(--border-color)' }}>
        {tabs.map((t) => (
          <button key={t.key}
            onClick={() => setTab(t.key)}
            style={{
              padding: '8px 16px', border: 'none', background: 'none', cursor: 'pointer',
              fontSize: 14, fontWeight: tab === t.key ? 600 : 400,
              color: tab === t.key ? 'var(--color-primary)' : 'var(--text-secondary)',
              borderBottom: tab === t.key ? '2px solid var(--color-primary)' : '2px solid transparent',
              transition: 'all 0.15s',
            }}
          >{t.label}</button>
        ))}
      </div>

      {tab === 'overview' && <OverviewTab features={features} learning={learning} />}
      {tab === 'emotion' && <EmotionTab emotion={emotion} features={features} />}
      {tab === 'decision' && <DecisionTab features={features} learning={learning} />}
    </div>
  )
}

// ---- Overview Tab ----

function OverviewTab({ features, learning }: { features: FeaturesViewModel | null; learning: LearningOverview | null }) {
  if (!features) return <Loading />

  return (
    <div>
      {/* Top stats row */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: 20 }}>
        <StatCard icon="📊" title="接受率" value={`${features.relationship.overall_accept_rate > 0 ? (features.relationship.overall_accept_rate * 100).toFixed(0) : '--'}%`} color="#1677ff" />
        <StatCard icon="💻" title="连续工作" value={features.user.continuous_work_min > 0 ? `${features.user.continuous_work_min.toFixed(0)}分钟` : '未工作'} color="#f59e0b" />
        <StatCard icon="📨" title="今日行动" value={`${learning?.metrics.total_today ?? '--'}次`} color="#10b981" />
        <StatCard icon="⚠️" title="最近拒绝" value={`${features.relationship.recent_rejections}次`} color="#ef4444" />
      </div>

      {/* Drives radar + Needs bars */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}>
        <div>
          <h3 style={{ fontSize: 14, marginBottom: 8, color: 'var(--text-secondary)' }}>5维驱力</h3>
          <RadarChart
            size={180}
            data={[
              { label: '社交', value: features.drives?.social ?? 0, color: '#f472b6' },
              { label: '关怀', value: features.drives?.care ?? 0, color: '#ef4444' },
              { label: '好奇', value: features.drives?.curious ?? 0, color: '#60a5fa' },
              { label: '安静', value: features.drives?.quiet ?? 0, color: '#a78bfa' },
              { label: '探索', value: features.drives?.explore ?? 0, color: '#34d399' },
            ]}
          />
        </div>
        <div>
          <h3 style={{ fontSize: 14, marginBottom: 8, color: 'var(--text-secondary)' }}>6维内源需求</h3>
          <NeedBars needs={features.needs} />
        </div>
      </div>

      {/* Quick relationship */}
      <div style={{ marginTop: 20 }}>
        <h3 style={{ fontSize: 14, marginBottom: 8, color: 'var(--text-secondary)' }}>互动关系</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12 }}>
          <MiniItem label="冷落时长" value={`${(features.relationship.neglect_hours * 60).toFixed(0)}分钟`} />
          <MiniItem label="消息趋势" value={features.user.length_trend < -0.2 ? '变短 ⬇' : features.user.length_trend > 0.2 ? '变长 ⬆' : '稳定'} />
          <MiniItem label="亲密度趋势" value={features.relationship.intimacy_trend < -0.1 ? '降温 ⬇' : features.relationship.intimacy_trend > 0.1 ? '升温 ⬆' : '稳定'} />
        </div>
      </div>
    </div>
  )
}

// ---- Emotion Tab ----

function EmotionTab({ emotion, features }: { emotion: EmotionViewModel | null; features: FeaturesViewModel | null }) {
  if (!emotion) return <Loading />
  const v = emotion.vector

  const emotionBars = [
    { label: '情感', value: v.affection, color: '#f472b6' },
    { label: '担忧', value: v.worry, color: '#fbbf24' },
    { label: '好奇', value: v.curiosity, color: '#60a5fa' },
    { label: '困倦', value: v.sleepiness, color: '#a78bfa' },
    { label: '贪玩', value: v.playfulness, color: '#34d399' },
    { label: '寂寞', value: v.loneliness, color: '#f87171' },
    { label: '自信', value: v.confidence, color: '#818cf8' },
    { label: '烦躁', value: v.annoyance, color: '#fb923c' },
  ]

  return (
    <div>
      <div style={{ display: 'flex', gap: 16, marginBottom: 16 }}>
        <div style={{
          width: 64, height: 64, borderRadius: '50%', background: 'var(--color-primary-light)',
          display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 28,
        }}>{emotionIcon(emotion.primary)}</div>
        <div>
          <div style={{ fontSize: 28, fontWeight: 700 }}>{labelPrimary(emotion.primary)}</div>
          <div style={{ fontSize: 13, color: 'var(--text-secondary)' }}>
            PAD: V{emotion.valence.toFixed(2)} A{emotion.arousal.toFixed(2)} D{emotion.dominance.toFixed(2)} · 强度{(emotion.intensity * 100).toFixed(0)}%
          </div>
          {features && <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 2 }}>
            趋势: {features.user?.length_trend ? (features.user.length_trend < 0 ? '↓ 变短' : '↑ 变长') : '--'}
          </div>}
        </div>
      </div>

      <h3 style={{ fontSize: 14, marginBottom: 8, color: 'var(--text-secondary)' }}>8维情绪向量</h3>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {emotionBars.map((e) => (
          <div key={e.label} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ width: 40, fontSize: 13, textAlign: 'right' }}>{e.label}</span>
            <div style={{ flex: 1, height: 16, background: 'var(--bg-muted)', borderRadius: 4, overflow: 'hidden' }}>
              <div style={{ height: '100%', width: `${(e.value * 100).toFixed(0)}%`, background: e.color, borderRadius: 4, transition: 'width 1s' }} />
            </div>
            <span style={{ width: 36, fontSize: 12, color: 'var(--text-muted)' }}>{(e.value * 100).toFixed(0)}%</span>
          </div>
        ))}
      </div>
    </div>
  )
}

// ---- Decision Tab ----

function DecisionTab({ features, learning }: { features: FeaturesViewModel | null; learning: LearningOverview | null }) {
  if (!features) return <Loading />

  const d = features.last_decision
  return (
    <div>
      <h3 style={{ fontSize: 14, marginBottom: 12, color: 'var(--text-secondary)' }}>最近决策溯源</h3>
      {d ? (
        <div style={{
          background: 'var(--bg-card)', border: '1px solid var(--border-color)',
          borderRadius: 8, padding: 16, marginBottom: 16,
        }}>
          <div style={{ fontSize: 18, fontWeight: 600, marginBottom: 8 }}>
            {actionLabel(d.action)} <span style={{ fontSize: 13, color: 'var(--text-muted)', fontWeight: 400 }}>score {d.score.toFixed(3)}</span>
          </div>
          <div style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            {d.routed_llm && '🧠 LLM 兜底决策 · '}
            来源: {d.source || '--'}
          </div>
          <div style={{ display: 'flex', gap: 8, marginTop: 8, flexWrap: 'wrap' }}>
            {d.routed_llm && <Badge color="#f59e0b">LLM</Badge>}
            {d.source === 'care' && <Badge color="#ef4444">关怀</Badge>}
            {d.source === 'casual' && <Badge color="#3b82f6">闲聊</Badge>}
            {d.source === 'knowledge_gap' && <Badge color="#8b5cf6">好奇</Badge>}
          </div>
        </div>
      ) : (
        <div style={{ color: 'var(--text-muted)', marginBottom: 16 }}>等待首次决策...</div>
      )}

      {/* Factor snapshot */}
      <h3 style={{ fontSize: 14, marginBottom: 8, color: 'var(--text-secondary)' }}>当前关键因子</h3>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
        <FactorRow label="App" value={`${features.user.app_category}(${features.user.window_subtype || '-'})`} />
        <FactorRow label="工作" value={features.user.is_working ? '是' : '否'} />
        <FactorRow label="时段接受率" value={`${(features.relationship.time_window_accept * 100).toFixed(0)}%`} />
        <FactorRow label="距上次消息" value={`${features.user.time_since_chat_min.toFixed(0)}分钟`} />
        <FactorRow label="策略/模式" value={`${features.task.principle_count}/${features.task.pattern_count}`} />
        <FactorRow label="冷却" value={`${(features.task.cooldown_norm * 100).toFixed(0)}%`} />
      </div>

      {/* Learning stats */}
      {learning && (
        <div style={{ marginTop: 20 }}>
          <h3 style={{ fontSize: 14, marginBottom: 8, color: 'var(--text-secondary)' }}>学习统计</h3>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 8 }}>
            <MiniItem label="策略" value={`${learning.principles_count}`} />
            <MiniItem label="线程" value={`${learning.active_threads}`} />
            <MiniItem label="inquiries" value={`${learning.active_inquiries}`} />
            <MiniItem label="模式" value={`${learning.patterns_count}`} />
          </div>
        </div>
      )}
    </div>
  )
}

// ---- Small Components ----

function NeedBars({ needs }: { needs: FeaturesViewModel['needs'] }) {
  const items = [
    { key: 'companionship', label: '陪伴', v: needs.companionship, color: '#f472b6' },
    { key: 'care', label: '关怀', v: needs.care, color: '#ef4444' },
    { key: 'play', label: '玩耍', v: needs.play, color: '#34d399' },
    { key: 'curiosity', label: '好奇', v: needs.curiosity, color: '#60a5fa' },
    { key: 'rest', label: '休息', v: needs.rest, color: '#a78bfa' },
    { key: 'autonomy', label: '自主', v: needs.autonomy, color: '#fbbf24' },
  ]
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
      {items.map((n) => (
        <div key={n.key} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ width: 36, fontSize: 12, textAlign: 'right' }}>{n.label}</span>
          <div style={{ flex: 1, height: 12, background: 'var(--bg-muted)', borderRadius: 3, overflow: 'hidden' }}>
            <div style={{ height: '100%', width: `${(n.v * 100).toFixed(0)}%`, background: n.color, borderRadius: 3, transition: 'width 0.8s' }} />
          </div>
          <span style={{ width: 32, fontSize: 11, color: 'var(--text-muted)' }}>
            {(n.v * 100).toFixed(0)}%{n.v > 0.7 ? ' ⚡' : ''}
          </span>
        </div>
      ))}
    </div>
  )
}

function MiniItem({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border-color)', borderRadius: 6, padding: '8px 12px' }}>
      <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{label}</div>
      <div style={{ fontSize: 15, fontWeight: 600 }}>{value}</div>
    </div>
  )
}

function FactorRow({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ fontSize: 13, display: 'flex', justifyContent: 'space-between', padding: '4px 0', borderBottom: '1px solid var(--border-color)' }}>
      <span style={{ color: 'var(--text-secondary)' }}>{label}</span>
      <span style={{ fontWeight: 500 }}>{value}</span>
    </div>
  )
}

function Badge({ color, children }: { color: string; children: string }) {
  return <span style={{ background: color + '18', color, padding: '2px 8px', borderRadius: 4, fontSize: 11, fontWeight: 600 }}>{children}</span>
}

function Loading() {
  return <div style={{ color: 'var(--text-muted)', padding: 40, textAlign: 'center' }}>加载中...</div>
}

function emotionIcon(primary: string) {
  const m: Record<string, string> = { joy: '😊', sadness: '😢', anger: '😠', fear: '😨', surprise: '😲', disgust: '🤢', neutral: '😐' }
  return m[primary] || '😐'
}

function labelPrimary(p: string) {
  const m: Record<string, string> = { joy: '开心', sadness: '难过', anger: '生气', fear: '恐惧', surprise: '惊讶', disgust: '厌恶', neutral: '平静' }
  return m[p] || p
}

function actionLabel(a: string) {
  const m: Record<string, string> = {
    speak_casual: '💬 闲聊', speak_care: '❤️ 关心', speak_inquiry: '❓ 提问',
    care_rest: '😴 催睡', care_meal: '🍚 催饭', care_hydration: '💧 催喝水',
    care_health: '🏃 健康提醒', care_encourage: '💪 鼓励', care_social: '👥 社交提醒',
    observe: '👀 观察', reflect: '🤔 反思', analyze_patterns: '📊 分析', none: '😴 安静',
  }
  return m[a] || a
}
