// frontend/src/pages/settings/ChatPage.tsx
import { useState, useCallback, useEffect, useRef } from 'react'
import ChatMessageList, { ChatMessage } from '../../components/settings/ChatMessageList'
import ChatInput from '../../components/settings/ChatInput'

const API_BASE = 'http://127.0.0.1:19840'

async function sendChatMessage(text: string): Promise<{ content: string; source?: string }> {
  const res = await fetch(`${API_BASE}/api/chat/send`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text }),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: `HTTP ${res.status}` }))
    throw new Error(err.error || `HTTP ${res.status}`)
  }
  return res.json()
}

interface HistoryResponse {
  messages: ChatMessage[]
  total: number
}

async function fetchHistory(): Promise<ChatMessage[]> {
  const res = await fetch(`${API_BASE}/api/chat/history?page=0&pageSize=30`)
  if (!res.ok) return []
  const data: HistoryResponse = await res.json()
  // API already returns oldest-first.
  return data.messages ?? []
}

function ChatPage() {
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [sending, setSending] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const sendingRef = useRef(false)

  // Load history on mount, then subscribe to SSE for real-time messages.
  useEffect(() => {
    let cancelled = false
    let es: EventSource | null = null

    fetchHistory()
      .then((msgs) => { if (!cancelled) setMessages(msgs) })
      .catch(() => {})
      .finally(() => { if (!cancelled) setLoading(false) })

    // Subscribe to SSE for real-time cross-window sync.
    const connectSSE = () => {
      es = new EventSource('http://127.0.0.1:19840/api/events')
      es.addEventListener('chat-message', (e: MessageEvent) => {
        if (cancelled || sendingRef.current) return
        try {
          const msg = JSON.parse(e.data)
          if (!msg.content) return
          // Use functional update to avoid race with handleSend's local add.
          setMessages((prev) => {
            const last = prev[prev.length - 1]
            if (last && last.content === msg.content && last.role === msg.role) return prev
            return [...prev, { role: msg.role, content: msg.content }]
          })
        } catch {}
      })
      es.onerror = () => {
        es?.close()
        if (!cancelled) setTimeout(connectSSE, 3000)
      }
    }
    connectSSE()

    return () => { cancelled = true; es?.close() }
  }, [])

  const handleSend = useCallback(async (text: string) => {
    setMessages((prev) => [...prev, { role: 'user', content: text }])
    setSending(true)
    sendingRef.current = true
    setError(null)
    try {
      const result = await sendChatMessage(text)
      setMessages((prev) => [...prev, {
        role: 'assistant',
        content: result.content,
        source: result.source,
      }])
    } catch (e: any) {
      setMessages((prev) => [...prev, {
        role: 'assistant',
        content: `[错误] ${e?.message || e}`,
      }])
      setError(e?.message || '发送失败')
    } finally {
      setSending(false)
      // Keep guard up briefly for late SSE events.
      setTimeout(() => { sendingRef.current = false }, 500)
    }
  }, [])

  return (
    <div style={{
      display: 'flex', flexDirection: 'column', height: '100%',
      background: 'var(--bg-card)', borderRadius: 'var(--radius-card)',
      boxShadow: 'var(--shadow-card)', overflow: 'hidden',
    }}>
      {/* Header */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '12px 16px', borderBottom: '1px solid var(--border-color)',
      }}>
        <span style={{ fontSize: 15, fontWeight: 600, color: 'var(--text-primary)' }}>
          {'\u{1F4AC} 与诗音聊天'}
        </span>
        {error && (
          <span style={{ fontSize: 12, color: 'var(--color-danger)' }}>
            {error}
          </span>
        )}
        {messages.length > 0 && (
          <button
            onClick={() => setMessages([])}
            style={{
              border: 'none', background: 'none',
              color: 'var(--text-muted)', fontSize: 12,
              cursor: 'pointer',
            }}
          >
            清空
          </button>
        )}
      </div>

      {/* Messages */}
      {loading ? (
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)' }}>
          加载对话记录...
        </div>
      ) : (
        <ChatMessageList messages={messages} streaming={sending} />
      )}

      {/* Input */}
      <ChatInput
        onSend={handleSend}
        disabled={sending}
        placeholder="输入消息... (Enter 发送, Shift+Enter 换行)"
      />
    </div>
  )
}

export default ChatPage

// frontend/src/pages/settings/ChatPage.vue
<template>
  <div class="chat-root">
    <!-- Fixed header -->
    <div class="chat-header">
      <span class="chat-title">与诗音聊天</span>
      <n-space align="center">
        <n-tag v-if="error" type="error" size="small" round :bordered="false">{{ error }}</n-tag>
        <n-button v-if="messages.length" text size="small" @click="messages = []">清空</n-button>
      </n-space>
    </div>

    <!-- Scrollable messages -->
    <div class="msg-list" ref="listRef">
      <n-spin v-if="loading" style="flex:1;display:flex;align-items:center;justify-content:center;" />
      <template v-else>
        <div v-if="messages.length === 0" class="empty-chat">开始和诗音聊天吧</div>
        <div v-for="(msg, i) in messages" :key="i" :class="['bubble', msg.role === 'user' ? 'user' : 'assistant']">
          <div v-if="msg.source || msg.observed" class="bubble-tags">
            <n-tag v-if="msg.source" :bordered="false" size="tiny" round>{{ sourceLabel(msg.source) }}</n-tag>
            <n-tag v-if="msg.observed" :bordered="false" size="tiny" round type="info">屏幕观察</n-tag>
          </div>
          <div class="bubble-text">{{ msg.content }}</div>
          <span v-if="sending && i === messages.length - 1 && msg.role !== 'user'" class="cursor-blink">|</span>
        </div>
      </template>
    </div>

    <!-- Fixed input bar -->
    <div class="chat-footer">
      <n-input
        v-model:value="inputText"
        type="textarea"
        :autosize="{ minRows: 2, maxRows: 4 }"
        placeholder="输入消息... (Enter 发送)"
        :disabled="sending"
        @keydown="onKeydown"
        @compositionstart="composing = true"
        @compositionend="onCompositionEnd"
      />
      <n-button type="primary" :disabled="sending || !inputText.trim()" @click="handleSend" style="margin-top:8px;align-self:flex-end;">
        <template #icon><n-icon><SendOutline /></n-icon></template>
        发送
      </n-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick, watch } from 'vue'
import { NButton, NInput, NTag, NSpace, NSpin, NIcon } from 'naive-ui'
import { SendOutline } from '@vicons/ionicons5'

const API_BASE = 'http://127.0.0.1:19840'

interface ChatMessage { role: 'user' | 'assistant'; content: string; source?: string; observed?: boolean }

const messages = ref<ChatMessage[]>([])
const sending = ref(false)
const error = ref<string | null>(null)
const loading = ref(true)
const inputText = ref('')
const composing = ref(false)
const listRef = ref<HTMLElement | null>(null)
let sendingGuard = false

watch(() => messages.value.length, () => nextTick(() => {
  listRef.value?.lastElementChild?.scrollIntoView({ behavior: 'smooth' })
}))

function onCompositionEnd() { composing.value = false; setTimeout(() => composing.value = false, 300) }
function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey && !composing.value) {
    e.preventDefault(); handleSend()
  }
}

onMounted(async () => {
  try {
    const res = await fetch(`${API_BASE}/api/chat/history?page=0&pageSize=30`)
    if (res.ok) { const data = await res.json(); messages.value = data.messages ?? [] }
  } catch {}
  loading.value = false

  let es: EventSource | null = null
  const connectSSE = () => {
    es = new EventSource('http://127.0.0.1:19840/api/events')
    es.addEventListener('chat-message', (e: MessageEvent) => {
      if (sendingGuard) return
      try {
        const msg = JSON.parse(e.data)
        if (!msg.content) return
        const last = messages.value[messages.value.length - 1]
        if (last && last.content === msg.content && last.role === msg.role) return
        messages.value = [...messages.value, { role: msg.role, content: msg.content }]
      } catch {}
    })
    es.onerror = () => { es?.close(); setTimeout(connectSSE, 3000) }
  }
  connectSSE()
  onUnmounted(() => es?.close())
})

async function handleSend() {
  const text = inputText.value.trim()
  if (!text) return
  messages.value = [...messages.value, { role: 'user', content: text }]
  inputText.value = ''
  sending.value = true; sendingGuard = true; error.value = null
  try {
    const res = await fetch(`${API_BASE}/api/chat/send`, {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }),
    })
    if (!res.ok) { const err = await res.json().catch(() => ({ error: `HTTP ${res.status}` })); throw new Error(err.error || `HTTP ${res.status}`) }
    const result = await res.json()
    messages.value = [...messages.value, { role: 'assistant', content: result.content, source: result.source }]
  } catch (e: any) {
    messages.value = [...messages.value, { role: 'assistant', content: `[错误] ${e?.message || e}` }]
    error.value = e?.message || '发送失败'
  } finally { sending.value = false; setTimeout(() => { sendingGuard = false }, 500) }
}

function sourceLabel(s: string) { const m: Record<string, string> = { care: '关心', knowledge_gap: '想了解你', foresight: '预测验证', casual: '闲聊' }; return m[s] || '' }
</script>

<style scoped>
.chat-root {
  height: calc(100vh - 64px);
  display: flex;
  flex-direction: column;
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.06);
}

/* ── fixed top ── */
.chat-header {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14px 20px;
  border-bottom: 1px solid #f3f4f6;
}
.chat-title { font-size: 15px; font-weight: 600; }

/* ── scrollable middle ── */
.msg-list {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  padding: 16px 20px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}
.empty-chat {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #9ca3af;
  font-size: 14px;
}

/* ── fixed bottom ── */
.chat-footer {
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  padding: 12px 20px;
  border-top: 1px solid #f3f4f6;
}

/* ── bubbles ── */
.bubble { max-width: 78%; padding: 10px 14px; border-radius: 14px; font-size: 14px; line-height: 1.6; white-space: pre-wrap; word-break: break-word; }
.bubble.user { align-self: flex-end; background: #4f6ef7; color: #fff; border-bottom-right-radius: 4px; }
.bubble.assistant { align-self: flex-start; background: #f3f4f6; color: #1a1a2e; border-bottom-left-radius: 4px; }
.bubble-tags { margin-bottom: 4px; display: flex; gap: 4px; }
.bubble-text { font-size: 14px; }
.cursor-blink { animation: blink 1s step-end infinite; color: #999; }
@keyframes blink { 50% { opacity: 0; } }
</style>
