// frontend/src/pages/settings/MemoryPage.vue
<template>
  <div class="page-root">
    <div class="sub-header">
      <div class="sub-title">记忆管理 · 共 {{ total }} 条</div>
      <n-input-group style="max-width: 340px;">
        <n-input v-model:value="searchInput" placeholder="搜索记忆..." size="small" clearable @keydown.enter="doSearch" />
        <n-button type="primary" size="small" @click="doSearch">搜索</n-button>
      </n-input-group>
    </div>

    <n-tabs v-model:value="layer" type="bar" animated @update:value="onLayerChange">
      <n-tab-pane name="" tab="全部" />
      <n-tab-pane name="L0" tab="L0 工作记忆" />
      <n-tab-pane name="L1" tab="L1 日记" />
      <n-tab-pane name="L2" tab="L2 语义事实" />
      <n-tab-pane name="L3" tab="L3 核心自我" />
    </n-tabs>

    <div v-if="error" class="msg-box"><n-text type="error">{{ error }}</n-text></div>
    <div v-if="!error && !loading && memories.length === 0" class="msg-box"><n-text depth="3">暂无记忆数据</n-text></div>

    <n-grid :cols="2" :x-gap="16" :y-gap="16" v-if="memories.length">
      <n-gi v-for="m in memories" :key="m.id">
        <n-card size="small" :bordered="false" class="mem-card">
          <template #header>
            <div class="mem-hd">
              <n-tag :color="{ color: LAYER_COLORS[m.layer] || '#999', textColor: '#fff' }" size="tiny" :bordered="false">{{ m.layer }}</n-tag>
              <span v-if="m.created_at" class="mem-time">{{ m.created_at }}</span>
            </div>
          </template>
          <n-ellipsis :line-clamp="expanded === m.id ? 20 : 3" :tooltip="false">
            {{ m.content }}
          </n-ellipsis>
          <n-progress :percentage="Math.round(m.weight * 100)" :height="3" :border-radius="2" :show-indicator="false" :color="LAYER_COLORS[m.layer] || '#999'" style="margin: 10px 0;" />
          <n-space>
            <n-button text size="tiny" @click="expanded = expanded === m.id ? null : m.id">{{ expanded === m.id ? '收起' : '展开' }}</n-button>
            <n-button v-if="m.layer === 'L2'" text size="tiny" type="error" @click="handleDelete(m.id)">删除</n-button>
          </n-space>
        </n-card>
      </n-gi>
    </n-grid>

    <n-spin v-if="loading" style="display:flex;justify-content:center;padding:24px;" />
    <div v-if="hasMore && !loading" style="text-align:center;padding:20px;">
      <n-button @click="loadMore" secondary>加载更多</n-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { NCard, NGrid, NGi, NTabs, NTabPane, NTag, NButton, NInput, NInputGroup, NProgress, NSpace, NSpin, NText, NEllipsis } from 'naive-ui'

const API_BASE = 'http://127.0.0.1:19840'
const LAYER_COLORS: Record<string, string> = { L0: '#52c41a', L1: '#1677ff', L2: '#722ed1', L3: '#eb2f96' }

interface MemoryItem { id: string; layer: string; content: string; weight: number; created_at?: string }

const layer = ref('')
const memories = ref<MemoryItem[]>([])
const total = ref(0)
const page = ref(0)
const loading = ref(true)
const error = ref<string | null>(null)
const query = ref('')
const searchInput = ref('')
const expanded = ref<string | null>(null)

const hasMore = computed(() => memories.value.length < total.value)

async function load(l: string, p: number, q: string) {
  loading.value = true; error.value = null
  try {
    const params = new URLSearchParams({ page: String(p), pageSize: '20' })
    if (l) params.set('layer', l)
    if (q) params.set('query', q)
    const res = await fetch(`${API_BASE}/api/memories?${params}`)
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const data = await res.json()
    if (p === 0) memories.value = data.memories; else memories.value = [...memories.value, ...data.memories]
    total.value = data.total
  } catch (e: any) { error.value = e?.message || '加载失败' }
  finally { loading.value = false }
}

function onLayerChange(l: string) { layer.value = l; page.value = 0; load(l, 0, query.value) }
function doSearch() { query.value = searchInput.value; page.value = 0; load(layer.value, 0, query.value) }
async function handleDelete(id: string) {
  if (!confirm('确定删除？')) return
  try {
    const res = await fetch(`${API_BASE}/api/memories/${id}`, { method: 'DELETE' })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    memories.value = memories.value.filter(m => m.id !== id); total.value--
  } catch (e: any) { error.value = e?.message || '删除失败' }
}
function loadMore() { const next = page.value + 1; page.value = next; load(layer.value, next, query.value) }

load('', 0, '')
</script>

<style scoped>
.page-root { height: 100%; overflow-y: auto; }
.sub-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 4px; }
.sub-title { font-size: 14px; color: #6b7280; }
.msg-box { text-align: center; padding: 40px; }
.mem-card :deep(.n-card__content) { padding-top: 0; }
.mem-hd { display: flex; align-items: center; justify-content: space-between; width: 100%; }
.mem-time { font-size: 11px; color: #9ca3af; }
</style>

// frontend/src/pages/settings/MemoryPage.tsx
import { useEffect, useState, useCallback } from 'react'
import LayerTabs, { LAYER_COLORS } from '../../components/settings/LayerTabs'
import { useSettingsStore } from '../../store/settingsStore'

const API_BASE = 'http://127.0.0.1:19840'

interface MemoryItem {
  id: string
  layer: string
  content: string
  weight: number
  created_at?: string
}

interface MemoryListResponse {
  memories: MemoryItem[]
  total: number
}

async function fetchMemories(layer: string, page: number, query?: string): Promise<MemoryListResponse> {
  const params = new URLSearchParams({ page: String(page), pageSize: '20' })
  if (layer) params.set('layer', layer)
  if (query) params.set('query', query)
  const res = await fetch(`${API_BASE}/api/memories?${params}`)
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  return res.json()
}

async function deleteMemory(id: string): Promise<void> {
  const res = await fetch(`${API_BASE}/api/memories/${id}`, { method: 'DELETE' })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
}

function MemoryPage() {
  const [layer, setLayer] = useState('')
  const [memories, setMemories] = useState<MemoryItem[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(0)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [query, setQuery] = useState('')
  const [searchInput, setSearchInput] = useState('')
  const [expanded, setExpanded] = useState<string | null>(null)
  const navigate = useSettingsStore((s) => s.navigate)

  const load = useCallback(async (l: string, p: number, q: string) => {
    setLoading(true)
    setError(null)
    try {
      const data = await fetchMemories(l, p, q || undefined)
      if (p === 0) {
        setMemories(data.memories)
      } else {
        setMemories((prev) => [...prev, ...data.memories])
      }
      setTotal(data.total)
    } catch (e: any) {
      setError(e?.message || '加载失败')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    setPage(0)
    load(layer, 0, query)
  }, [layer, query])

  const handleSearch = () => {
    setQuery(searchInput)
  }

  const handleDelete = async (id: string) => {
    if (!confirm('确定删除这条记忆？')) return
    try {
      await deleteMemory(id)
      setMemories((prev) => prev.filter((m) => m.id !== id))
      setTotal((t) => t - 1)
    } catch (e: any) {
      setError(e?.message || '删除失败')
    }
  }

  const loadMore = () => {
    const next = page + 1
    setPage(next)
    load(layer, next, query)
  }

  const hasMore = memories.length < total

  return (
    <div>
      <div style={{ fontSize: 20, fontWeight: 600, color: 'var(--text-primary)', marginBottom: 16 }}>
        {'\u{1F9E0} 记忆管理'}
        <span style={{ fontSize: 12, color: 'var(--text-muted)', marginLeft: 8 }}>
          共 {total} 条
        </span>
      </div>

      {/* Tabs */}
      <LayerTabs active={layer} onChange={setLayer} />

      {/* Search */}
      <div style={{ display: 'flex', gap: 8, marginBottom: 20 }}>
        <input
          type="text"
          value={searchInput}
          onChange={(e) => setSearchInput(e.target.value)}
          onKeyDown={(e) => { if (e.key === 'Enter') handleSearch() }}
          placeholder="搜索记忆..."
          style={{
            flex: 1, height: 36,
            border: '1px solid var(--border-color)',
            borderRadius: 'var(--radius-input)',
            padding: '0 12px', fontSize: 14, outline: 'none', maxWidth: 400,
          }}
        />
        <button
          onClick={handleSearch}
          style={{
            padding: '0 16px', height: 36,
            border: '1px solid var(--border-color)',
            borderRadius: 'var(--radius-input)',
            background: '#fff', fontSize: 13, cursor: 'pointer',
          }}
        >
          搜索
        </button>
      </div>

      {/* Content */}
      {error && (
        <div style={{ background: 'var(--bg-card)', borderRadius: 'var(--radius-card)', padding: 32, textAlign: 'center', marginBottom: 16 }}>
          <p style={{ color: 'var(--color-danger)' }}>{error}</p>
        </div>
      )}

      {!error && !loading && memories.length === 0 && (
        <div style={{ background: 'var(--bg-card)', borderRadius: 'var(--radius-card)', padding: 48, textAlign: 'center' }}>
          <p style={{ color: 'var(--text-muted)' }}>暂无记忆数据</p>
        </div>
      )}

      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: 12,
      }}>
        {memories.map((m) => {
          const isOpen = expanded === m.id
          return (
            <div
              key={m.id}
              style={{
                background: 'var(--bg-card)',
                borderRadius: 'var(--radius-card)',
                padding: 16,
                boxShadow: 'var(--shadow-card)',
                borderLeft: `3px solid ${LAYER_COLORS[m.layer] || '#999'}`,
              }}
            >
              {/* Layer badge + time */}
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                <span style={{
                  fontSize: 11, fontWeight: 600, color: '#fff',
                  background: LAYER_COLORS[m.layer] || '#999',
                  padding: '2px 8px', borderRadius: 4,
                }}>
                  {m.layer}
                </span>
                {m.created_at && (
                  <span style={{ fontSize: 11, color: 'var(--text-muted)', marginLeft: 'auto' }}>
                    {m.created_at}
                  </span>
                )}
              </div>

              {/* Content */}
              <p style={{
                fontSize: 13, color: 'var(--text-primary)',
                lineHeight: 1.6, margin: '0 0 8px',
                whiteSpace: isOpen ? 'pre-wrap' : 'normal',
                overflow: isOpen ? 'visible' : 'hidden',
                display: isOpen ? 'block' : '-webkit-box',
                WebkitLineClamp: isOpen ? undefined : 3,
                WebkitBoxOrient: 'vertical',
              }}>
                {m.content}
              </p>

              {/* Weight bar */}
              <div style={{ height: 3, background: '#f0f0f0', borderRadius: 2, marginBottom: 10, overflow: 'hidden' }}>
                <div style={{
                  width: (m.weight * 100) + '%',
                  height: '100%',
                  background: LAYER_COLORS[m.layer] || '#999',
                  borderRadius: 2,
                  transition: 'width 0.3s',
                }} />
              </div>

              {/* Actions */}
              <div style={{ display: 'flex', gap: 8 }}>
                <button
                  onClick={() => setExpanded(isOpen ? null : m.id)}
                  style={{
                    border: '1px solid var(--border-color)',
                    borderRadius: 'var(--radius-input)',
                    background: '#fff', fontSize: 12, padding: '4px 10px',
                    cursor: 'pointer', color: 'var(--text-secondary)',
                  }}
                >
                  {isOpen ? '收起' : '展开'}
                </button>
                {m.layer === 'L2' && (
                  <button
                    onClick={() => handleDelete(m.id)}
                    style={{
                      border: 'none',
                      borderRadius: 'var(--radius-input)',
                      background: '#fff1f0', fontSize: 12, padding: '4px 10px',
                      cursor: 'pointer', color: 'var(--color-danger)',
                      marginLeft: 'auto',
                    }}
                  >
                    删除
                  </button>
                )}
              </div>
            </div>
          )
        })}
      </div>

      {loading && (
        <div style={{ textAlign: 'center', padding: 20, color: 'var(--text-muted)' }}>加载中...</div>
      )}
      {hasMore && !loading && (
        <div style={{ textAlign: 'center', padding: 20 }}>
          <button onClick={loadMore} style={{
            padding: '8px 24px',
            border: '1px solid var(--border-color)',
            borderRadius: 'var(--radius-input)',
            background: '#fff', fontSize: 13, cursor: 'pointer',
          }}>
            加载更多
          </button>
        </div>
      )}
    </div>
  )
}

export default MemoryPage
