// frontend/src/components/settings/Sidebar.vue
<template>
  <n-layout-sider
    bordered
    :width="240"
    :native-scrollbar="false"
    class="sider"
    collapse-mode="width"
  >
    <!-- Brand -->
    <div class="brand">
      <div class="brand-icon">
        <n-icon size="28" color="#fff"><PawOutline /></n-icon>
      </div>
      <div class="brand-text">
        <div class="brand-name">诗音</div>
        <div class="brand-ver">Desktop Pet v0.5</div>
      </div>
    </div>

    <!-- Menu -->
    <n-menu
      :value="settings.currentPage"
      :options="menuOptions"
      @update:value="settings.navigate($event)"
    />

    <!-- Model Selector -->
    <div class="model-area" v-if="models.length > 1">
      <div class="model-label">Live2D 模型</div>
      <n-select
        v-model:value="selectedModel"
        :options="modelOptions"
        size="small"
        @update:value="onModelChange"
      />
    </div>

    <!-- Open Pet button -->
    <div class="sider-footer">
      <n-button type="primary" block @click="handleOpenPet" secondary>
        <template #icon><n-icon><PlayOutline /></n-icon></template>
        打开宠物
      </n-button>
    </div>
  </n-layout-sider>
</template>

<script setup lang="ts">
import { ref, onMounted, h, computed } from 'vue'
import { NLayoutSider, NMenu, NSelect, NButton, NIcon } from 'naive-ui'
import {
  SpeedometerOutline, ChatbubblesOutline, BookOutline, GlobeOutline,
  HammerOutline, SettingsOutline, AppsOutline, PulseOutline,
  PawOutline, PlayOutline, BulbOutline, FileTrayFullOutline,
} from '@vicons/ionicons5'
import { useSettingsStore } from '../../stores/settingsStore'
import { usePetStore } from '../../stores/petStore'
import { getModels, ModelInfo } from '../../stores/api'
import type { MenuOption } from 'naive-ui'

const settings = useSettingsStore()
const pet = usePetStore()

const icon = (icon: any) => () => h(NIcon, null, { default: () => h(icon) })

const menuOptions: MenuOption[] = [
  { label: '仪表盘', key: 'dashboard', icon: icon(SpeedometerOutline) },
  { label: '执行状态', key: 'observability', icon: icon(PulseOutline) },
  { label: '对话面板', key: 'chat', icon: icon(ChatbubblesOutline) },
  { label: '日记', key: 'diary', icon: icon(BookOutline) },
  { label: '记忆图谱', key: 'memory', icon: icon(GlobeOutline) },
  { label: '策略实验室', key: 'strategy-lab', icon: icon(BulbOutline) },
  { label: 'API 配置', key: 'api', icon: icon(SettingsOutline) },
  { label: '插件', key: 'plugins', icon: icon(AppsOutline) },
]

const models = ref<ModelInfo[]>([])
const selectedModel = ref(pet.modelPath)

const modelOptions = computed(() =>
  models.value.map(m => ({ label: m.name, value: m.path }))
)

onMounted(async () => {
  try { models.value = await getModels() } catch {}
})

function onModelChange(path: string) {
  pet.setModelPath(path)
  setTimeout(() => window.location.reload(), 200)
}

function handleOpenPet() {
  try { (window as any).go?.main?.SettingsApp?.OpenPet() } catch {}
}
</script>

<style scoped>
.sider {
  height: 100vh;
  display: flex;
  flex-direction: column;
}
.brand {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 24px 20px 20px;
  border-bottom: 1px solid rgba(0,0,0,0.06);
}
.brand-icon {
  width: 40px; height: 40px;
  border-radius: 10px;
  background: linear-gradient(135deg, #4f6ef7, #6b85f9);
  display: flex; align-items: center; justify-content: center;
}
.brand-name {
  font-size: 18px; font-weight: 700;
  color: #1a1a2e; line-height: 1.2;
}
.brand-ver {
  font-size: 11px; color: #9ca3af;
}
.model-area {
  padding: 12px 20px;
  border-top: 1px solid rgba(0,0,0,0.06);
}
.model-label {
  font-size: 11px; color: #9ca3af;
  margin-bottom: 6px; text-transform: uppercase; letter-spacing: 0.5px;
}
.sider-footer {
  padding: 12px 16px 20px;
  border-top: 1px solid rgba(0,0,0,0.06);
  margin-top: auto;
}
</style>

// desktop-pet/frontend/src/components/settings/Sidebar.tsx
import { useEffect, useState } from 'react'
import { useSettingsStore } from '../../store/settingsStore'
import { getModels, ModelInfo } from '../../store/api'
import { usePetStore } from '../../store'

const menuItems = [
  { key: 'dashboard',      icon: '\u{1F4CA}', label: '仪表盘' },
  { key: 'observability',  icon: '\u{1F52D}', label: '执行状态' },
  { key: 'chat',           icon: '\u{1F4AC}', label: '对话面板' },
  { key: 'diary',          icon: '\u{1F4D6}', label: '日记' },
  { key: 'memory',         icon: '\u{1F9E0}', label: '记忆图谱' },
  { key: 'strategy-lab',   icon: '\u{1F9EA}', label: '策略实验室' },
  { key: 'api',            icon: '\u{2699}\u{FE0F}', label: 'API 配置' },
  { key: 'plugins',        icon: '\u{1F9E9}', label: '插件' },
]

function Sidebar() {
  const currentPage = useSettingsStore((s) => s.currentPage)
  const navigate = useSettingsStore((s) => s.navigate)

  const handleOpenPet = () => {
    try {
      const go = (window as any).go
      if (go?.main?.SettingsApp?.OpenPet) {
        go.main.SettingsApp.OpenPet()
      }
    } catch {
      // silently ignore if Wails binding not available
    }
  }

  return (
    <aside style={{
      width: 220, minWidth: 220, height: '100vh',
      background: 'var(--bg-sidebar)', borderRight: '1px solid var(--border-color)',
      display: 'flex', flexDirection: 'column', userSelect: 'none',
    }}>
      <div style={{ padding: 20 }}>
        <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ fontSize: 20 }}>{'\u{1F431}'}</span>
          {'诗音 · 设置'}
        </div>
        <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>Desktop Pet v0.5.0</div>
      </div>

      <nav style={{ flex: 1, overflowY: 'auto', padding: '8px 0' }}>
        {menuItems.map((item) => {
          const active = currentPage === item.key
          return (
            <div key={item.key} onClick={() => navigate(item.key)}
              style={{
                display: 'flex', alignItems: 'center', padding: '10px 16px', margin: '2px 8px',
                borderRadius: 8, cursor: 'pointer', transition: 'all 0.15s ease',
                color: active ? 'var(--color-primary)' : 'var(--text-secondary)',
                background: active ? 'var(--color-primary-light)' : 'transparent',
                fontWeight: active ? 600 : 400,
              }}
              onMouseEnter={(e) => { if (!active) { e.currentTarget.style.background = '#e5e7eb'; e.currentTarget.style.color = 'var(--text-primary)' } }}
              onMouseLeave={(e) => { if (!active) { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.color = 'var(--text-secondary)' } }}
            >
              <span style={{ fontSize: 16, width: 20, textAlign: 'center', flexShrink: 0 }}>{item.icon}</span>
              <span style={{ marginLeft: 12, fontSize: 14 }}>{item.label}</span>
            </div>
          )
        })}
      </nav>

      <ModelSelector />

      <div style={{ padding: '0 8px 16px' }}>
        <div style={{ borderTop: '1px solid var(--border-color)', margin: '8px 8px 12px' }} />
        <button onClick={handleOpenPet} style={{
          width: '100%', padding: '10px 16px', border: 'none', borderRadius: 8,
          background: 'var(--color-primary)', color: '#fff', fontWeight: 600,
          fontSize: 14, cursor: 'pointer', transition: 'background 0.15s ease',
        }} onMouseEnter={(e) => { e.currentTarget.style.background = '#0958d9' }}
          onMouseLeave={(e) => { e.currentTarget.style.background = 'var(--color-primary)' }}>
          {'\u{1F431} 打开宠物'}
        </button>
      </div>
    </aside>
  )
}

function ModelSelector() {
  const [models, setModels] = useState<ModelInfo[]>([])
  const modelPath = usePetStore((s) => s.modelPath)
  const setModelPath = usePetStore((s) => s.setModelPath)

  useEffect(() => { getModels().then(setModels).catch(() => {}) }, [])
  if (models.length < 2) return null

  return (
    <div style={{ padding: '8px 16px' }}>
      <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>模型</div>
      <select value={modelPath} onChange={(e) => { setModelPath(e.target.value); setTimeout(() => window.location.reload(), 200) }}
        style={{ width: '100%', padding: '6px 8px', borderRadius: 6, border: '1px solid var(--border-color)', fontSize: 12, background: 'var(--bg-card)', color: 'var(--text-primary)', cursor: 'pointer' }}>
        {models.map((m) => <option key={m.path} value={m.path}>{m.name}</option>)}
      </select>
    </div>
  )
}

export default Sidebar
